### ISSUE TITLE
kmaslack/hhvm-stats extension fails to build on glibc 2.19-0ubuntu6.11

### ISSUE THREAD

**Issue by pdbogen** [facebook/hhvm#7780]
### HHVM Version

master

### Standalone code, or other way to reproduce the problem

Build HHVM; build https://github.com/kmaslack/hhvm-stats; observed compile time error.

### Expected result

Extension builds without error.

### Actual result

```
$ make
[  8%] Building CXX object CMakeFiles/stats.dir/php_stats.cpp.o
/home/jenkinsslave/extensions/stats/php_stats.cpp: In function 'void zif_stats_stat_factorial(int, zval*, zval**, zval*, int, void***)':
/home/jenkinsslave/extensions/stats/php_stats.cpp:3415:7: error: 'isinf' was not declared in this scope
   if (zend_isinf(f)) {
       ^
/home/jenkinsslave/extensions/stats/php_stats.cpp:3415:7: note: suggested alternative:
In file included from /usr/include/c++/5/complex:44:0,
                 from /usr/include/boost/type_traits/is_complex.hpp:12,
                 from /usr/include/boost/type_traits.hpp:49,
                 from /home/jenkinsslave/target/include/hphp/third-party/folly/String.h:24,
                 from /home/jenkinsslave/target/include/hphp/util/thread-local.h:24,
                 from /home/jenkinsslave/target/include/hphp/runtime/ext_zend_compat/php-src/Zend/../TSRM/TSRM.h:124,
                 from /home/jenkinsslave/target/include/hphp/runtime/ext_zend_compat/php-src/Zend/zend_alloc.h:27,
                 from /home/jenkinsslave/target/include/hphp/runtime/ext_zend_compat/php-src/Zend/zend.h:252,
                 from /home/jenkinsslave/target/include/hphp/runtime/ext_zend_compat/php-src/main/php.h:34,
                 from /home/jenkinsslave/extensions/stats/php_stats.cpp:26:
/usr/include/c++/5/cmath:621:5: note:   'std::isinf'
     isinf(_Tp __x)
     ^
CMakeFiles/stats.dir/build.make:278: recipe for target 'CMakeFiles/stats.dir/php_stats.cpp.o' failed
make[2]: *** [CMakeFiles/stats.dir/php_stats.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/stats.dir/all' failed
make[1]: *** [CMakeFiles/stats.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
```

This appears to be the same problem as described in 6924. The offending line in this case is https://github.com/facebook/hhvm/blob/master/hphp/runtime/base/zend-php-config.h#L2409.

This code also exists in os-specific compat headers:
https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext_zend_compat/php-src/main/php_config-darwin.h#L2469
https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext_zend_compat/php-src/main/php_config-linux.h#L2458
https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext_zend_compat/php-src/main/php_config-msvc.h#L2463

This is a linux build, so maybe php_config-linux.h is the *actual* culprit. I *suspect* that darwin and msvc may not need to be changed.

**Comment by lexidor** [comment]
This extension is no longer maintained. Closing this issue as it is unlikely that Keith will update the extension to work with hhvm at HEAD.
