### ISSUE TITLE
3.15.3 Source version fails to build on OSX 10.12.2

### ISSUE THREAD

**Issue by xssworm** [facebook/hhvm#7560]
### HHVM Version 3.15.3
[log.txt](https://github.com/facebook/hhvm/files/659768/log.txt)

**Comment by daviddoran** [comment]
Same `call__frame undefined` error reported in hhvm/homebrew-hhvm:
https://github.com/hhvm/homebrew-hhvm/issues/63

Also reported in a few comments:

https://github.com/hhvm/homebrew-hhvm/issues/58#issuecomment-266383256
https://github.com/hhvm/homebrew-hhvm/issues/58#issuecomment-264884024
https://gist.github.com/robopuff/6693eb1bd5f03a4d4a9ba58c0bdf6a11#gistcomment-1948094

**Comment by mofarrell** [comment]
Master incorporated a fix for this in august.  Either use an older version of ocaml, or cherrypick https://github.com/facebook/hhvm/commit/28eefc45ef093c0d81e62375bd7cb22eb6d4b947#diff-762268a3020b817fe6204b4dc7188494 before building
A mode where we could disable building hack might be nice.  In this case the error is not occuing in the hhvm, but still breaks it.

**Comment by xssworm** [comment]
not only ocaml 4.0.4, I had tested ocaml 4.0.1, 4.0.2, 4.0.3, all of above occurs this error

**Comment by mofarrell** [comment]
This `caml__frame` issue should not be a problem in versions before 4.04
Perhaps there are other issues though.  Do you have another log?

**Comment by daviddoran** [comment]
I eventually managed to build HHVM successfully by reverting my OCaml version. Used something like these commands (though I probably missed some because it was trial-and-error):

```
brew unlink ocamlbuild
brew switch ocaml 4.02.3
brew link --overwrite ocamlbuild
opam switch 4.02.3
brew upgrade hhvm
```

**Comment by xssworm** [comment]
thanks @daviddoran  
It works.

**Comment by mkillianey** [comment]
FWIW, I didn't happen to have an pre-4.04 ocaml installed, so my workaround was:
```
HOMEBREW_CORE=/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
OCAML_FORMULA=Formula/ocaml.rb
brew uninstall ocaml ocamlbuild
# Get the recipe for ocaml 4.03
curl https://raw.githubusercontent.com/Homebrew/homebrew-core/6c6d86c7c0f9f0881650b9a11c5ce6c61e7b9824/$OCAML_FORMULA \
  > $HOMEBREW_CORE/$OCAML_FORMULA
# Install hhvm using 4.03
brew install ocaml ocamlbuild hhvm
# Restore ocaml 4.04 recipe so brew repo isn't dirty
git -C $HOMEBREW_CORE checkout -- $OCAML_FORMULA
```
This worked for me on OSX 10.11.6.

**Comment by lplofchan** [comment]
@mkillianey thanks for posting this, i was just trying to figure out how to change the version of ocaml without anything installed. but when i try to do that curl command, i keep getting the following message `"-bash: /: Is a directory" `

do i need to edit that curl command at all?

**Comment by mkillianey** [comment]
It sounds like these didn't take effect:

HOMEBREW_CORE=/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
OCAML_FORMULA=Formula/ocaml.rb

Because this line:

curl https://raw.githubusercontent.com/Homebrew/homebrew-core/6c6d86c7c0f9f0881650b9a11c5ce6c61e7b9824/$OCAML_FORMULA
\
  > $HOMEBREW_CORE/$OCAML_FORMULA

Should expand to something like:

curl https://raw.githubusercontent.com/Homebrew/homebrew-core/6c6d86c7c0f9f0881650b9a11c5ce6c61e7b9824/$OCAML_FORMULA
\
  > /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ocaml.rb

If you haven't done any customization with respect to where homebrew lives
on your system, you can probably just cut and paste the expanded line.

**Comment by lplofchan** [comment]
@mkillianey you are right, i incorrectly missed the HOMEBREW_CORE=/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
line.

while that did allow me to curl and start installing hhvm, i still ended up with an error that said this: 
`[ 54%] Building CXX object hphp/runtime/CMakeFiles/hphp_runtime_static.dir/base/memory-manager.cpp.o
[ 54%] Building CXX object hphp/runtime/CMakeFiles/hphp_runtime_static.dir/base/mixed-array.cpp.o
[ 54%] Building CXX object hphp/runtime/CMakeFiles/hphp_runtime_static.dir/base/object-data.cpp.o
In file included from /tmp/hhvm-20170102-1775-13m2n6d/hhvm-3.15.3/hphp/runtime/base/object-data.cpp:32:
In file included from /tmp/hhvm-20170102-1775-13m2n6d/hhvm-3.15.3/hphp/runtime/ext/simplexml/ext_simplexml.h:22:
/tmp/hhvm-20170102-1775-13m2n6d/hhvm-3.15.3/hphp/runtime/ext/libxml/ext_libxml.h:23:10: fatal error: 'libxml/parser.h' file not found
#include <libxml/parser.h>
         ^
[ 54%] Building CXX object hphp/runtime/CMakeFiles/hphp_runtime_static.dir/base/output-file.cpp.o

[ 55%] Building CXX object hphp/runtime/CMakeFiles/hphp_runtime_static.dir/base/packed-array.cpp.o

1 error generated.

make[2]: *** [hphp/runtime/CMakeFiles/hphp_runtime_static.dir/base/object-data.cpp.o] Error 1

make[2]: *** Waiting for unfinished jobs....

make[1]: *** [hphp/runtime/CMakeFiles/hphp_runtime_static.dir/all] Error 2

make: *** [all] Error 2
`

I am somehow missing some files from the libxml directory, i think. do you have any idea of what is causing this problem/how to fix it? thank you so much!

**Comment by mofarrell** [comment]
This has been fixed in august 28eefc45ef093c0d81e62375bd7cb22eb6d4b947.  It will not be experienced on HHVM master.  This fix will not be backported to the LTS releases as of now.  It seems most people are having issues during the homebrew installation.  This will be fixed when we bump to 3.17.1 (hopefully soon).  There is also an [issue](https://github.com/hhvm/homebrew-hhvm/issues/63) tracking this in the homebrew repo.
