### ISSUE TITLE
unable to build with GCC 4.8.2 ( issue with jpeg-9 & bundle libgd)

### ISSUE THREAD

**Issue by coronanimo** [facebook/hhvm#2284]
Can make after modification to /hphp/runtime/CMakeFiles/hphp_runtime_static.dir/build.make

Compiler:
Reading specs from /home/opt/compiler/gcc-4.8.2.09/bin/../lib/gcc/x86_64-baidu-linux-gnu/4.8.2/specs
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/home/opt/compiler/gcc-4.8.2.09/bin/../libexec/gcc/x86_64-baidu-linux-gnu/4.8.2/lto-wrapper
Target: x86_64-baidu-linux-gnu
Configured with: ../configure CFLAGS=-O2 --host=x86_64-baidu-linux-gnu --target=x86_64-baidu-linux-gnu --prefix=/top --with-sysroot --with-local-prefix=/ --with-native-system-header-dir=/top/include --with-build-sysroot=/top --with-system-libunwind --enable-languages=c,c++ --enable-c99 --enable-threads=posix --enable-__cxa_atexit --enable-libstdcxx-allocator --enable-libstdcxx-threads --enable-libstdcxx-time --enable-libstdcxx-visibility --disable-multilib --disable-bootstrap
Thread model: posix
gcc version 4.8.2 (GCC) 

[ 54%] Building CXX object hphp/runtime/CMakeFiles/hphp_runtime_static.dir/ext/gd/libgd/gd_png.cpp.o
/home/hushiwei/hhvm/hhvm-HHVM-3.0.1/hphp/runtime/ext/gd/libgd/gd_jpeg.cpp: In function 'void jpeg_gdIOCtx_src(j_decompress_ptr, gdIOCtx_)':
/home/hushiwei/hhvm/hhvm-HHVM-3.0.1/hphp/runtime/ext/gd/libgd/gd_jpeg.cpp:721:29: error: invalid conversion from 'safeboolean (_)(j_decompress_ptr) {aka int (_)(jpeg_decompress_struct_)}' to 'boolean (_)(j_decompress_ptr) {aka boolean (_)(jpeg_decompress_struct_)}' [-fpermissive]
  src->pub.fill_input_buffer = fill_input_buffer;
                             ^
/home/hushiwei/hhvm/hhvm-HHVM-3.0.1/hphp/runtime/ext/gd/libgd/gd_jpeg.cpp: In function 'void jpeg_gdIOCtx_dest(j_compress_ptr, gdIOCtx_)':
/home/hushiwei/hhvm/hhvm-HHVM-3.0.1/hphp/runtime/ext/gd/libgd/gd_jpeg.cpp:841:32: error: invalid conversion from 'safeboolean (_)(j_compress_ptr) {aka int (_)(jpeg_compress_struct_)}' to 'boolean (_)(j_compress_ptr) {aka boolean (_)(jpeg_compress_struct_)}' [-fpermissive]
  dest->pub.empty_output_buffer = empty_output_buffer;
                                ^
make[2]: **\* [hphp/runtime/CMakeFiles/hphp_runtime_static.dir/ext/gd/libgd/gd_jpeg.cpp.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
