### ISSUE TITLE
please help: meet error when compile on RHEL6.3

### ISSUE THREAD

**Issue by jimmydong** [facebook/hhvm#648]
In file included from /root/hiphop-php/src/runtime/vm/translator/targetcache.h:22:0,
                 from /root/hiphop-php/src/runtime/base/intercept.cpp:22:
/root/hiphop-php/src/runtime/vm/translator/asm-x64.h:362:20: error: uninitialized const ‘HPHP::VM::Transl::reg::rip’ [-fpermissive]

RHEL6.3 x64 , gcc 4.6.1
