### ISSUE TITLE
Compilation Problem (mcrouter) -- HHVM fails to build with gcc 4.9

### ISSUE THREAD

**Issue by UnsecPhu** [facebook/hhvm#5438]
> [  0%] Built target timelib
> [  0%] Built target double-conversion
> [  7%] Built target folly
> [ 12%] Built target hphp_proxygen
> [ 16%] Built target hphp_thrift
> [ 16%] Built target afdt
> [ 16%] Built target eaw_table
> [ 22%] Built target mbfl
> [ 26%] Built target re2
> [ 27%] Built target webscalesqlclient
> [ 28%] Built target squangle
> [ 28%] Building CXX object third-party/mcrouter/CMakeFiles/mcrouter.dir/mcrouter/mcrouter_config.cpp.o
> /usr/local/hhvm/third-party/mcrouter/mcrouter/mcrouter_config.cpp: In function ‘std::unordered_map<std::basic_string<char>, folly::dynamic> facebook::memcache::mcrouter::additionalConfigParams()’:
> /usr/local/hhvm/third-party/mcrouter/mcrouter/mcrouter_config.cpp:91:11: error: converting to ‘std::unordered_map<std::basic_string<char>, folly::dynamic>’ from initializer list would use explicit constructor ‘std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Key = std::basic_string<char>; _Tp = folly::dynamic; _Hash = std::hash<std::basic_string<char> >; _Pred = std::equal_to<std::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, folly::dynamic> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::hasher = std::hash<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::pair<const std::basic_string<char>, folly::dynamic> >]’
>    return {};
>                ^
> make[2]: *** [third-party/mcrouter/CMakeFiles/mcrouter.dir/mcrouter/mcrouter_config.cpp.o] Error 1
> make[1]: *** [third-party/mcrouter/CMakeFiles/mcrouter.dir/all] Error 2
> make: *** [all] Error 2

I tried replacing the files witht he one from mcrouter repo and it still didnt work.

> cmake version 3.0.2
> GNU Make 3.81
> gcc version 4.9.2 (GCC)

**Comment by jwatzman** [comment]
Caused by https://github.com/facebook/hhvm/commit/1740e8cc6b14b550441c88509d6d6ca2602e270c -- it works on gcc 4.8 but not 4.9 I think. I'm looking now.

**Comment by jwatzman** [comment]
Landing D2118922 into the internal mcrouter repo now, should be sync'd out later today, at which point I can do some more submodule bumps. Stand by. :)
