### ISSUE TITLE
Registering autoloaders from autoloaders does not as expected

### ISSUE THREAD

**Issue by willemstuursma** [facebook/hhvm#5701]
Imagine a situation where an autoloader does not know how to load a class, but it does know which autoloader does so it registers the new autoloader.

In HHVM, registering an autoloader while loading a class using the `spl_autoload_register()` function does not work. The newly registered autoloader is not called. This does work in PHP 5.6.11.

Example code:

``` php
<?php
class Autoloader1
{
    public static function autoload ($class)
    {
        var_dump("Loading {$class} from " . __CLASS__);

        spl_autoload_register(["Autoloader2", "autoload"]);
    }
}
class Autoloader2
{
    public static function autoload ($class)
    {
        var_dump("Loading {$class} from " . __CLASS__);exit;
    }
}

spl_autoload_register(["Autoloader1", "autoload"]);

$r = new Foo();
```

Output from PHP 5.6.11:

```
string(28) "Loading Foo from Autoloader1"
string(28) "Loading Foo from Autoloader2"

Fatal error: Class undefined: Foo in /var/www/willem/tests/hhvmautoload.php on line 26
```

Output from HHVM 3.8.0

```
string(28) "Loading Foo from Autoloader1"

Fatal error: Class undefined: Foo in /var/www/willem/tests/hhvmautoload.php on line 26
```

Note how the second autoloader is not called in the HHVM example.

**Comment by photodude** [comment]
Still an issue in 3.12.0 - 3.14.4
https://3v4l.org/7gp1b#vhhvm-3120 I assume still an issue in 3.15.2 and 3.16.0-dev

**Comment by photodude** [comment]
Confirmed as still an issue in HHVM 3.15.2 and HHVM 3.16.0-dev
see travis build comparing php and hhvm
https://travis-ci.org/photodude/HHVM_memory_test/builds/168473135

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The `\spl_autoload_register()` function and the infra around it is no longer present in hhvm.
See [hhvm/hhvm-autoload@v3.1.0](https://github.com/hhvm/hhvm-autoload/releases/tag/v3.1.0) release notes.
