### ISSUE TITLE
Can't build with boost 1.52 on Gentoo

### ISSUE THREAD

**Issue by kristapsk** [facebook/hhvm#1291]
After upgrading boost to 1.52, had problems with compiling HHVM:

```
Linking CXX executable test
../../bin/libhphp_util.a(util.cpp.o): In function `boost::filesystem3::remove_all(boost::filesystem3::path const&)':
/usr/include/boost/filesystem/v3/operations.hpp:502: undefined reference to `boost::filesystem3::detail::remove_all(boost::filesystem3::path const&, boost::system::error_code*)'
collect2: error: ld returned 1 exit status
make[2]: *** [hphp/hhvm/hhvm] Error 1
make[1]: *** [hphp/hhvm/CMakeFiles/hhvm.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
../../bin/libhphp_util.a(util.cpp.o): In function `boost::filesystem3::remove_all(boost::filesystem3::path const&)':
/usr/include/boost/filesystem/v3/operations.hpp:502: undefined reference to `boost::filesystem3::detail::remove_all(boost::filesystem3::path const&, boost::system::error_code*)'
collect2: error: ld returned 1 exit status
make[2]: *** [hphp/test/test] Error 1
make[1]: *** [hphp/test/CMakeFiles/test.dir/all] Error 2
make: *** [all] Error 2
```

Replacing CMake/FindBoost.cmake with the version from CMake 2.8.11.2 solved this issue for me.

So, it seems either FindBoost.cmake should be updated or documentation should specifiy latest boost version number that can be used with hhvm.
