### ISSUE TITLE
Build errors on Ubuntu

### ISSUE THREAD

**Issue by nazar-pc** [facebook/hhvm#7027]
I'm on master branch (b7f1a0c), builds on Ubuntu 14.04, 15.10 and 16.04 all fail with various errors (while a week ago or so I was able to compile HHVM with the same local software at least on 15.10 and 16.04 using Docker image, now failures are in the same Docker images that worked before).

Here is what fails with 15.10 and 16.04:
```
[  4%] Building CXX object third-party/re2/CMakeFiles/re2.dir/src/re2/onepass.cc.o
/hhvm/third-party/ragel/src/ragel/common.cpp:38:1: error: narrowing conversion of '18446744073709551615ul' from 'long unsigned int' to 'long long int' inside { } [-Wnarrowing]
 };
 ^
/hhvm/third-party/ragel/src/ragel/common.cpp:92:1: error: narrowing conversion of '18446744073709551615ull' from 'long long unsigned int' to 'long long int' inside { } [-Wnarrowing]
 };
 ^
/hhvm/third-party/ragel/src/ragel/common.cpp:120:1: error: narrowing conversion of '18446744073709551615ul' from 'long unsigned int' to 'long long int' inside { } [-Wnarrowing]
 };
 ^
third-party/ragel/CMakeFiles/ragel.dir/build.make:446: recipe for target 'third-party/ragel/CMakeFiles/ragel.dir/src/ragel/common.cpp.o' failed
make[2]: *** [third-party/ragel/CMakeFiles/ragel.dir/src/ragel/common.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

I've tried to use older `third-party` submodule and older master branch, but can't find where it works, looks like everything from last week fails to build.

I'm using following Docker image for building HHVM: https://github.com/nazar-pc/docker-build-hhvm

**Comment by Orvid** [comment]
The reason for this is me adding ragel in to generate some stuff in mcrouter, and I fixed this with a commit to third-party earlier today. If you point your third party to master you should be able to build just fine. The reference to third-party in the main HHVM repo hasn't been updated yet to see that change.

**Comment by nazar-pc** [comment]
Thanks, it seems to work with third-party master. However, the whole compilation will take some time)

**Comment by nazar-pc** [comment]
On Ubuntu 15.10 still have compilation errors:
```
Building CXX object hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/imagick/imagickdraw.cpp.o
In file included from /usr/include/ImageMagick-6/wand/MagickWand.h:29:0,
                 from /hhvm/hphp/runtime/ext/imagick/ext_imagick.h:25,
                 from /hhvm/hphp/runtime/ext/imagick/imagickpixeliterator.cpp:18:
/usr/include/ImageMagick-6/magick/magick-config.h:21:38: fatal error: magick/magick-baseconfig.h: No such file or directory
compilation terminated.
In file included from /usr/include/ImageMagick-6/wand/MagickWand.h:29:0,
                 from /hhvm/hphp/runtime/ext/imagick/ext_imagick.h:25,
                 from /hhvm/hphp/runtime/ext/imagick/imagick.cpp:18:
/usr/include/ImageMagick-6/magick/magick-config.h:21:38: fatal error: magick/magick-baseconfig.h: No such file or directory
In file included from /usr/include/ImageMagick-6/wand/MagickWand.h:29:0,
                 from /hhvm/hphp/runtime/ext/imagick/ext_imagick.h:25,
                 from /hhvm/hphp/runtime/ext/imagick/imagickdraw.cpp:18:
/usr/include/ImageMagick-6/magick/magick-config.h:21:38: fatal error: magick/magick-baseconfig.h: No such file or directory
In file included from /usr/include/ImageMagick-6/wand/MagickWand.h:29:0,
                 from /hhvm/hphp/runtime/ext/imagick/ext_imagick.h:25,
                 from /hhvm/hphp/runtime/ext/imagick/imagickpixel.cpp:18:
/usr/include/ImageMagick-6/magick/magick-config.h:21:38: fatal error: magick/magick-baseconfig.h: No such file or directory
compilation terminated.
compilation terminated.
In file included from /usr/include/ImageMagick-6/wand/MagickWand.h:29:0,
                 from /hhvm/hphp/runtime/ext/imagick/ext_imagick.h:25,
                 from /hhvm/hphp/runtime/ext/imagick/ext_imagick.cpp:18:
/usr/include/ImageMagick-6/magick/magick-config.h:21:38: fatal error: magick/magick-baseconfig.h: No such file or directory
compilation terminated.
hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/build.make:3964: recipe for target 'hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/imagick/imagickpixeliterator.cpp.o' failed
make[2]: *** [hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/imagick/imagickpixeliterator.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
compilation terminated.
hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/build.make:3872: recipe for target 'hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/imagick/ext_imagick.cpp.o' failed
make[2]: *** [hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/imagick/ext_imagick.cpp.o] Error 1
hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/build.make:3918: recipe for target 'hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/imagick/imagickdraw.cpp.o' failed
make[2]: *** [hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/imagick/imagickdraw.cpp.o] Error 1
hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/build.make:3941: recipe for target 'hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/imagick/imagickpixel.cpp.o' failed
make[2]: *** [hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/imagick/imagickpixel.cpp.o] Error 1
hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/build.make:3895: recipe for target 'hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/imagick/imagick.cpp.o' failed
make[2]: *** [hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/imagick/imagick.cpp.o] Error 1
In file included from /usr/include/ImageMagick-6/wand/MagickWand.h:29:0,
                 from /hhvm/hphp/runtime/ext/imagick/ext_imagick.h:25,
                 from /hhvm/hphp/runtime/ext/imagick/constants.cpp:19:
/usr/include/ImageMagick-6/magick/magick-config.h:21:38: fatal error: magick/magick-baseconfig.h: No such file or directory
compilation terminated.
hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/build.make:3849: recipe for target 'hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/imagick/constants.cpp.o' failed
make[2]: *** [hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/imagick/constants.cpp.o] Error 1
CMakeFiles/Makefile2:1715: recipe for target 'hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/all' failed
make[1]: *** [hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by nazar-pc** [comment]
Similarly on Ubuntu 16.04:
```
[ 93%] Building CXX object hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/imagick/constants.cpp.o
In file included from /usr/include/ImageMagick-6/wand/MagickWand.h:29:0,
                 from /hhvm/hphp/runtime/ext/imagick/ext_imagick.h:25,
                 from /hhvm/hphp/runtime/ext/imagick/constants.cpp:19:
/usr/include/ImageMagick-6/magick/magick-config.h:21:38: fatal error: magick/magick-baseconfig.h: No such file or directory
compilation terminated.
hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/build.make:4022: recipe for target 'hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/imagick/constants.cpp.o' failed
make[2]: *** [hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/imagick/constants.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by Orvid** [comment]
Hrmm... Could you try reverting 8863fc10a10d1b9375a4f05314455b8dfbc9e32d locally and building? It's a rather large change in how we're compiling the CMake side, but it shouldn't be effecting any include paths.

**Comment by nazar-pc** [comment]
Result is exactly the same

**Comment by nazar-pc** [comment]
```
ln -s /usr/include/x86_64-linux-gnu/ImageMagick-6/magick/magick-baseconfig.h /usr/include/ImageMagick-6/magick/magick-baseconfig.h
```

```
[100%] Built target hphp_runtime_static
make[2]: *** No rule to make target '/usr/lib64/libxslt.so', needed by 'hphp/hhvm/hhvm'.  Stop.
CMakeFiles/Makefile2:2375: recipe for target 'hphp/hhvm/CMakeFiles/hhvm.dir/all' failed
make[1]: *** [hphp/hhvm/CMakeFiles/hhvm.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

```
mkdir /usr/lib64
ln -s /usr/lib/x86_64-linux-gnu/libxslt.so.1.1.28 /usr/lib64/libxslt.so
```

```
[100%] Built target hphp_runtime_static
make[2]: *** No rule to make target '/usr/lib64/libMagickWand-6.Q16.so', needed by 'hphp/hhvm/hhvm'.  Stop.
CMakeFiles/Makefile2:2375: recipe for target 'hphp/hhvm/CMakeFiles/hhvm.dir/all' failed
make[1]: *** [hphp/hhvm/CMakeFiles/hhvm.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

```
ln -s /usr/lib/x86_64-linux-gnu/libMagickWand-6.Q16.so /usr/lib64/libMagickWand-6.Q16.so
```

```
[100%] Built target hphp_runtime_static
make[2]: *** No rule to make target '/usr/lib64/libMagickCore-6.Q16.so', needed by 'hphp/hhvm/hhvm'.  Stop.
CMakeFiles/Makefile2:2375: recipe for target 'hphp/hhvm/CMakeFiles/hhvm.dir/all' failed
make[1]: *** [hphp/hhvm/CMakeFiles/hhvm.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Built target hack
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

```
ln -s /usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so /usr/lib64/libMagickCore-6.Q16.so
```

And finally I've got working binary.

**Comment by aorenste** [comment]
Is this still a problem?

**Comment by nazar-pc** [comment]
Didn't try for a long time (and it takes some time to compile to make it right now), will check again till the end of the week and let you know

**Comment by aorenste** [comment]
@nazar-pc Okay - I'm going to close this for now and if you discover that it's still a problem feel free to add more details and reopen.
