### ISSUE TITLE
Make error building on CentOS 6.3 

### ISSUE THREAD

**Issue by buley** [facebook/hhvm#654]
Hello Sara/everyone, thanks for the hard work. I'm working to build on CentOS 6.3. The error I'm running into seems to trace from `variable_unserializer` and `make` dumps the following:

Scanning dependencies of target hphp_runtime_static
[ 12%] Building CXX object src/CMakeFiles/hphp_runtime_static.dir/runtime/base/variable_unserializer.cpp.o
[ 12%] Building CXX object src/CMakeFiles/hphp_runtime_static.dir/runtime/base/variable_table.cpp.o
[ 12%] Building CXX object src/CMakeFiles/hphp_runtime_static.dir/runtime/base/variable_serializer.cpp.o
In file included from /dev/hiphop-php/src/runtime/vm/func.h:21,
                 from /dev/hiphop-php/src/runtime/vm/funcdict.h:20,
                 from /dev/hiphop-php/src/runtime/base/execution_context.h:28,
                 from /dev/hiphop-php/src/runtime/base/variable_serializer.cpp:18:
/dev/hiphop-php/src/runtime/vm/type_constraint.h:43: error: ISO C++ forbids declaration of ‘constexpr’ with no type
/dev/hiphop-php/src/runtime/vm/type_constraint.h:43: error: expected ‘;’ before ‘bool’
/dev/hiphop-php/src/runtime/vm/type_constraint.h:46: error: expected ‘;’ before ‘constexpr’
/dev/hiphop-php/src/runtime/vm/type_constraint.h:46: error: ISO C++ forbids declaration of ‘constexpr’ with no type
/dev/hiphop-php/src/runtime/vm/type_constraint.h:46: error: expected ‘;’ before ‘bool’
/dev/hiphop-php/src/runtime/vm/type_constraint.h:49: error: expected ‘;’ before ‘}’ token
/dev/hiphop-php/src/runtime/vm/type_constraint.h: In member function ‘bool HPHP::VM::TypeConstraint::isSelf() const’:
/dev/hiphop-php/src/runtime/vm/type_constraint.h:71: error: ‘const struct HPHP::VM::TypeConstraint::Type’ has no member named ‘isSelf’
/dev/hiphop-php/src/runtime/vm/type_constraint.h: In member function ‘bool HPHP::VM::TypeConstraint::isParent() const’:
/dev/hiphop-php/src/runtime/vm/type_constraint.h:75: error: ‘const struct HPHP::VM::TypeConstraint::Type’ has no member named ‘isParent’
make[2]: **\* [src/CMakeFiles/hphp_runtime_static.dir/runtime/base/variable_serializer.cpp.o] Error 1
make[1]: **\* [src/CMakeFiles/hphp_runtime_static.dir/all] Error 2
make: **\* [all] Error 2

[root@li574-24 hiphop-php]# cat /etc/redhat-release 
CentOS release 6.3 (Final)

I'm using a vanilla 6.3 image from Linode and working from the guide (https://github.com/facebook/hiphop-php/wiki).

I know you folks test on Ubuntu  but our production systems use CentOS so I wanted to take a stab at that. I've searched for an existing solution and believe this to be a new issue, or at least one without much documentation around it.

the shipped gcc is version 4.4.6 not 4.3 -- could that be the issue? any pointers would be appreciated. thank you.

[root@li574-24 hiphop-php]# gcc -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.6 20120305 (Red Hat 4.4.6-4) (GCC) 

Per other issues (https://github.com/facebook/hiphop-php/issues/633) I've done  "rm -f CMakeCache.txt" and "make clean" if I needed to make or cmake.
