### ISSUE TITLE
Undefined reference to c_Continuation::destruct(), c_Closure::destruct()

### ISSUE THREAD

**Issue by saracen** [facebook/hhvm#349]
Think this was introduced in https://github.com/facebook/hiphop-php/commit/315df2f4016357105548d1f5e50fb9ceef269430

Fixed with: https://gist.github.com/1017168
