### ISSUE TITLE
Support for Ubuntu 16.10

### ISSUE THREAD

**Issue by tslettebo** [facebook/hhvm#7489]
We've recently upgraded our servers to Ubuntu 16.10, and found that there are no prebuilt packages of HHVM for Ubuntu 16.10, neither are there any instructions for building them.

We're so far only using HHVM on our development server, but as we use to upgrade to the latest version of Ubuntu when it comes, the lack of a corresponding HHVM package available could make it hard for us to actually start using HHVM on our live servers.

Therefore, I'm wondering: Are there any plans for more closely tracking the Ubuntu releases with corresponding HHVM packages, and/or instructions for building from source?

I'd also like to know what we might do to build it for 16.10, or if possibly the 16.04 packages may be used.

**Comment by photodude** [comment]
possibly related to issues with 16.04 #7470

**Comment by Orvid** [comment]
#7470 is unrelated to this. HHVM should (probably) build fine on 16.10 by following the instructions for 16.04. The 16.04 package is very unlikely to work on 16.10.

We typically don't release packages for a new version of Ubuntu until the first release of HHVM after the Ubuntu release. This is primarily due to the pain of getting our packaging system setup for each new distro, but we do have plans in the works to make this significantly easier, at which point we'll look into adding pre-release versions of Ubuntu into the mix so that HHVM packages are available when each new version is officially released.

**Comment by tslettebo** [comment]
Thanks for your responses. Unfortunately, trying to build 16.10 using the 16.04 instructions resulted in various compilation errors.

Also, you're right, the 16.04 package didn't work on 16.10, due to its dependencies on specific versions of other packages, which had been updated in 16.10.

As mentioned, so far, we're only using HHVM for development, and we can take having a break in that work until someone figures out a way of making HHVM work on 16.10.

However, I'm happy that you guys are considering making pre-releases available, so that it's available when each version is officially released.

**Comment by nazar-pc** [comment]
16.04 packages do work on 16.10 if you manually install all necessary dependencies that are not present in repos anymore. It even works on 17.04 (as of now), but already started causing some conflicts with other packages.

**Comment by HRMsimon** [comment]
There's now been two releases since 16.10 was released (3.15.4, 3.17.0) but there still aren't any 16.10 packages.

**Comment by aorenste** [comment]
@HRMsimon I've been trying to automate and improve our build process.  Adding support for 16.10 is part of that so hopefully these will start releasing soon (maybe as soon as this week).

**Comment by alex-mashin** [comment]
> The 16.04 package is very unlikely to work on 16.10.

It does, though crashes often. But I am pretty sure, it would crash under 16.04 as well.

**Comment by 08ski11s** [comment]
keep in mind:

https://wiki.ubuntu.com/Releases

https://www.ubuntu.com/info/release-end-of-life

**Comment by soundslocke** [comment]
The [latest HHVM release apparently added support for Ubuntu 16.10](http://hhvm.com/blog/2017/02/15/hhvm-3-18.html).

I wonder if HHVM releases will arrive soon after (or even before?) Ubuntu releases going forward? This 4-month delay was odd.

**Comment by aorenste** [comment]
@soundslocke We've had some trouble with our build systems recently (also the reason for the nightly builds being out of commission) and I've been upgrading the process.  Once that's done (hopefully soon) we should be in a better position to add support for new versions (and possibly new distributions) going forward.

**Comment by soundslocke** [comment]
@aorenste That's great, thanks for the update :)

**Comment by tslettebo** [comment]
This is great news. Unfortunately, trying to install HHVM on Ubuntu 16.10 ran into some problems.

When running this command: sudo apt-get install hhvm

I get this output at the end:

----
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 hhvm : Depends: libboost-filesystem1.58.0 but it is not installable
        Depends: libboost-program-options1.58.0 but it is not installable
        Depends: libboost-system1.58.0 but it is not installable
        Depends: libboost-system1.58.0 but it is not installable
        Depends: libboost-regex1.58.0 but it is not installable
        Depends: libicu55 but it is not installable
        Depends: libboost-thread1.58.0 but it is not installable
        Depends: libboost-context1.58.0 but it is not installable
E: Unable to correct problems, you have held broken packages.
----

We've earlier triet to install HHVM for Ubuntu 16.04 on 16.10, and ran into some problems with Boost then. It's possible that this may be related to something we did to get that working. However, I'm not sure what our sysadmin did in this case.

Does anybody have any idea how we might solve this issue?

Doing "sudo apt-get install libboost-filesystem1.58.0" gives this error message:

Package libboost-filesystem1.58.0 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libboost-filesystem1.58.0' has no installation candidate

**Comment by aorenste** [comment]
@tslettebo The 16.10 distribution isn't quiet working yet - the dependencies are broken - hopefully the release this weekend should fix it.

**Comment by soundslocke** [comment]
Any word on a new release to fix the broke dependencies?

**Comment by aorenste** [comment]
@soundslocke The 3.18.1 release should have fixed the dependencies.

**Comment by nazar-pc** [comment]
Why is this closed? `hhvm-nightly` still is not available there.

**Comment by Orvid** [comment]
This issue was specifically for 16.10 being packaged. The nightlies are still not running, but packages for 16.10 are being built.
