### ISSUE TITLE
[Fedora] hhvm not compiling against memcached 1.0.16

### ISSUE THREAD

**Issue by nareshv** [facebook/hhvm#1022]
I was following https://raw.github.com/facebook/hiphop-php/master/hphp/NEWS and  when i upgrade memcached to 1.0.16 and compile, the following errors show up. Are we really ready for 1.0.9+ of libmemcached ?

OS: Centos 6.4, x86_64 , GCC 4.6.3
Commit: 13ddbb4ec17cffeeaaa83940016e6811cd71b387

Same code was compiled against memcached-0.49 which did go well http://www.hop5.in/yum/el6/repoview/hiphop-php.html

[ 33%] Building CXX object hphp/CMakeFiles/hphp_runtime_static.dir/runtime/ext/ext_memcached.cpp.o
hhvm/hphp/runtime/ext/ext_memcached.cpp: In function 'memcached_return_t HPHP::{anonymous}::doServerListCallback(const memcached_st_, const memcached_instance_st_, void_)':
hhvm/hphp/runtime/ext/ext_memcached.cpp:613:26: error: cannot convert 'const memcached_instance_st_' to 'memcached_server_instance_st {aka const org::libmemcached::Instance_}' for argument '1' to 'const char_ memcached_server_name(memcached_server_instance_st)'
hhvm/hphp/runtime/ext/ext_memcached.cpp:614:20: error: cannot convert 'const memcached_instance_st_' to 'memcached_server_instance_st {aka const org::libmemcached::Instance_}' for argument '1' to 'in_port_t memcached_server_port(memcached_server_instance_st)'
hhvm/hphp/runtime/ext/ext_memcached.cpp: In member function 'HPHP::Array HPHP::c_Memcached::t_getserverlist()':
hhvm/hphp/runtime/ext/ext_memcached.cpp:629:66: error: invalid conversion from 'memcached_return_t (_)(const memcached_st_, const memcached_instance_st_, void_)' to 'memcached_server_function {aka memcached_return_t (_)(const memcached_st_, const org::libmemcached::Instance_, void_)}' [-fpermissive]
hhvm/hphp/runtime/ext/ext_memcached.cpp: In member function 'HPHP::Variant HPHP::c_Memcached::t_getserverbykey(HPHP::CStrRef)':
hhvm/hphp/runtime/ext/ext_memcached.cpp:643:70: error: cannot convert 'memcached_server_instance_st {aka const org::libmemcached::Instance_}' to 'const memcached_instance_st_' in initialization
hhvm/hphp/runtime/ext/ext_memcached.cpp:649:26: error: cannot convert 'const memcached_instance_st_' to 'memcached_server_instance_st {aka const org::libmemcached::Instance_}' for argument '1' to 'const char\* memcached_server_name(memcached_server_instance_st)'
hhvm/hphp/runtime/ext/ext_memcached.cpp:650:20: error: cannot convert 'const memcached_instance_st_' to 'memcached_server_instance_st {aka const org::libmemcached::Instance_}' for argument '1' to 'in_port_t memcached_server_port(memcached_server_instance_st)'
hhvm/hphp/runtime/ext/ext_memcached.cpp: In function 'memcached_return_t HPHP::{anonymous}::doStatsCallback(const memcached_st_, const memcached_instance_st_, void_)': 
hhvm/hphp/runtime/ext/ext_memcached.cpp:698:26: error: cannot convert 'const memcached_instance_st_' to 'memcached_server_instance_st {aka const org::libmemcached::Instance_}' for argument '1' to 'const char_ memcached_server_name(memcached_server_instance_st)'
hhvm/hphp/runtime/ext/ext_memcached.cpp:699:20: error: cannot convert 'const memcached_instance_st_' to 'memcached_server_instance_st {aka const org::libmemcached::Instance_}' for argument '1' to 'in_port_t memcached_server_port(memcached_server_instance_st)'
hhvm/hphp/runtime/ext/ext_memcached.cpp: In member function 'HPHP::Variant HPHP::c_Memcached::t_getstats()':
hhvm/hphp/runtime/ext/ext_memcached.cpp:745:61: error: invalid conversion from 'memcached_return_t (_)(const memcached_st_, const memcached_instance_st_, void_)' to 'memcached_server_function {aka memcached_return_t (_)(const memcached_st_, const org::libmemcached::Instance_, void_)}' [-fpermissive]
hhvm/hphp/runtime/ext/ext_memcached.cpp: In function 'memcached_return_t HPHP::{anonymous}::doVersionCallback(const memcached_st_, const memcached_instance_st_, void_)':
hhvm/hphp/runtime/ext/ext_memcached.cpp:759:26: error: cannot convert 'const memcached_instance_st_' to 'memcached_server_instance_st {aka const org::libmemcached::Instance_}' for argument '1' to 'const char_ memcached_server_name(memcached_server_instance_st)'
hhvm/hphp/runtime/ext/ext_memcached.cpp:760:20: error: cannot convert 'const memcached_instance_st_' to 'memcached_server_instance_st {aka const org::libmemcached::Instance_}' for argument '1' to 'in_port_t memcached_server_port(memcached_server_instance_st)'
hhvm/hphp/runtime/ext/ext_memcached.cpp:761:26: error: cannot convert 'const memcached_instance_st_' to 'memcached_server_instance_st {aka const org::libmemcached::Instance_}' for argument '1' to 'uint8_t memcached_server_major_version(memcached_server_instance_st)'
hhvm/hphp/runtime/ext/ext_memcached.cpp:762:26: error: cannot convert 'const memcached_instance_st_' to 'memcached_server_instance_st {aka const org::libmemcached::Instance_}' for argument '1' to 'uint8_t memcached_server_minor_version(memcached_server_instance_st)'
hhvm/hphp/runtime/ext/ext_memcached.cpp:763:26: error: cannot convert 'const memcached_instance_st_' to 'memcached_server_instance_st {aka const org::libmemcached::Instance_}' for argument '1' to 'uint8_t memcached_server_micro_version(memcached_server_instance_st)'
hhvm/hphp/runtime/ext/ext_memcached.cpp: In member function 'HPHP::Variant HPHP::c_Memcached::t_getversion()':
hhvm/hphp/runtime/ext/ext_memcached.cpp:778:63: error: invalid conversion from 'memcached_return_t (_)(const memcached_st_, const memcached_instance_st_, void_)' to 'memcached_server_function {aka memcached_return_t (_)(const memcached_st_, const org::libmemcached::Instance_, void_)}' [-fpermissive]
make[2]: **\* [hphp/CMakeFiles/hphp_runtime_static.dir/runtime/ext/ext_memcached.cpp.o] Error 1
make[1]: **\* [hphp/CMakeFiles/hphp_runtime_static.dir/all] Error 2
make: **\* [all] Error 2
