### ISSUE TITLE
Build fails for Ubuntu 15.10

### ISSUE THREAD

**Issue by lbadger** [facebook/hhvm#6410]
When trying to compile in Ubuntu 15.10 (Wily) The build fails at 100%

```
[100%] [100%] [100%] Building CXX object hphp/hhvm/CMakeFiles/hhvm.dir/main.cpp.o
Building CXX object hphp/hhvm/CMakeFiles/hhvm.dir/global-variables.cpp.o
Building CXX object hphp/hhvm/CMakeFiles/hhvm.dir/process-init.cpp.o
Linking CXX executable hhvm
../runtime/libhphp_runtime.a(preg.cpp.o):preg.cpp:function std::string* google::MakeCheckOpString<double, double>(double const&, double const&, char const*): error: undefined reference to 'google::base::CheckOpMessageBuilder::NewString()'
../runtime/libhphp_runtime.a(preg.cpp.o):preg.cpp:function std::string* google::MakeCheckOpString<HPHP::StringData const*, HPHP::StringData const*>(HPHP::StringData const* const&, HPHP::StringData const* const&, char const*): error: undefined reference to 'google::base::CheckOpMessageBuilder::NewString()'
../runtime/libhphp_runtime.a(timezone.cpp.o):timezone.cpp:function std::string* google::MakeCheckOpString<char const*, char const*>(char const* const&, char const* const&, char const*): error: undefined reference to 'google::base::CheckOpMessageBuilder::NewString()'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:function boost::program_options::typed_value<bool, char>::xparse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&) const: error: undefined reference to 'boost::program_options::validate(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool*, int)'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:function boost::program_options::typed_value<std::string, char>::xparse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&) const: error: undefined reference to 'boost::program_options::validate(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, std::string*, int)'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:function boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::string const&, std::string const&, int): error: undefined reference to 'boost::program_options::validation_error::get_template(boost::program_options::validation_error::kind_t)'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:function boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::string const&, std::string const&, int): error: undefined reference to 'boost::program_options::error_with_option_name::error_with_option_name(std::string const&, std::string const&, std::string const&, int)'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:function boost::program_options::basic_command_line_parser<char>::basic_command_line_parser(int, char const* const*): error: undefined reference to 'boost::program_options::to_internal(std::string const&)'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:function boost::program_options::basic_command_line_parser<char>::basic_command_line_parser(int, char const* const*): error: undefined reference to 'boost::program_options::detail::cmdline::cmdline(std::vector<std::string, std::allocator<std::string> > const&)'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:function boost::program_options::basic_command_line_parser<char>::basic_command_line_parser(int, char const* const*): error: undefined reference to 'boost::program_options::to_internal(std::string const&)'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:function boost::program_options::typed_value<bool, char>::name() const: error: undefined reference to 'boost::program_options::arg'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:function void boost::program_options::validate<std::string, char>(boost::any&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::string, std::allocator<std::string> >*, int): error: undefined reference to 'boost::program_options::validate(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, std::string*, int)'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:function void boost::program_options::validate<std::string, char>(boost::any&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::string, std::allocator<std::string> >*, int): error: undefined reference to 'boost::program_options::invalid_option_value::invalid_option_value(std::string const&)'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:function void boost::program_options::validate<int, char>(boost::any&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, int*, long): error: undefined reference to 'boost::program_options::invalid_option_value::invalid_option_value(std::string const&)'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:function HPHP::execute_program_impl(int, char**): error: undefined reference to 'boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:function HPHP::execute_program_impl(int, char**): error: undefined reference to 'boost::program_options::option_description::long_name() const'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:function HPHP::execute_program_impl(int, char**): error: undefined reference to 'boost::program_options::option_description::format_name() const'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:vtable for boost::exception_detail::error_info_injector<boost::program_options::invalid_option_value>: error: undefined reference to 'boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:vtable for boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::invalid_option_value> >: error: undefined reference to 'boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:vtable for boost::exception_detail::error_info_injector<boost::program_options::validation_error>: error: undefined reference to 'boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:vtable for boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::validation_error> >: error: undefined reference to 'boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:vtable for boost::program_options::typed_value<std::string, char>: error: undefined reference to 'boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:vtable for boost::program_options::typed_value<std::vector<std::string, std::allocator<std::string> >, char>: error: undefined reference to 'boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:vtable for boost::program_options::typed_value<int, char>: error: undefined reference to 'boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:vtable for boost::program_options::typed_value<bool, char>: error: undefined reference to 'boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
../runtime/libhphp_runtime.a(static-string-table.cpp.o):static-string-table.cpp:function std::string* google::MakeCheckOpString<long, long>(long const&, long const&, char const*): error: undefined reference to 'google::base::CheckOpMessageBuilder::NewString()'
../compiler/libhphp_analysis.a(compiler.cpp.o):compiler.cpp:function HPHP::prepareOptions(HPHP::CompilerOptions&, int, char**): error: undefined reference to 'boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
../hhbbc/libhphp_hhbbc.a(main.cpp.o):main.cpp:function HPHP::HHBBC::main(int, char**): error: undefined reference to 'boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
../hhbbc/libhphp_hhbbc.a(main.cpp.o):main.cpp:function HPHP::HHBBC::main(int, char**): error: undefined reference to 'boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
../hhbbc/libhphp_hhbbc.a(main.cpp.o):main.cpp:function HPHP::HHBBC::main(int, char**): error: undefined reference to 'boost::program_options::detail::cmdline::set_additional_parser(boost::function1<std::pair<std::string, std::string>, std::string const&>)'
../hhbbc/libhphp_hhbbc.a(main.cpp.o):main.cpp:function void boost::program_options::validate<unsigned long, char>(boost::any&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, unsigned long*, long): error: undefined reference to 'boost::program_options::invalid_option_value::invalid_option_value(std::string const&)'
../hhbbc/libhphp_hhbbc.a(main.cpp.o):main.cpp:function void boost::program_options::validate<unsigned int, char>(boost::any&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, unsigned int*, long): error: undefined reference to 'boost::program_options::invalid_option_value::invalid_option_value(std::string const&)'
collect2: error: ld returned 1 exit status
hphp/hhvm/CMakeFiles/hhvm.dir/build.make:362: recipe for target 'hphp/hhvm/hhvm' failed
make[2]: *** [hphp/hhvm/hhvm] Error 1
CMakeFiles/Makefile2:2105: recipe for target 'hphp/hhvm/CMakeFiles/hhvm.dir/all' failed
make[1]: *** [hphp/hhvm/CMakeFiles/hhvm.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by JoelMarcey** [comment]
We don't officially support 15.10 yet. 15.04 is our latest officially supported Ubuntu distro. I imagine your `boost` version meets requirements -- what version do you have?

**Comment by lbadger** [comment]
15.10 also install GCC version ```gcc-5 (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010``` version, but I've also tried using ```gcc-4.9 (Ubuntu 4.9.3-5ubuntu1) 4.9.3```

```
libboost-atomic1.58-dev:amd64
libboost-atomic1.58.0:amd64
libboost-chrono1.58-dev:amd64
libboost-chrono1.58.0:amd64
libboost-context-dev:amd64
libboost-context1.54.0:amd64
libboost-context1.58-dev:amd64
libboost-context1.58.0:amd64
libboost-coroutine1.58-dev:amd64
libboost-date-time1.58-dev:amd64
libboost-date-time1.58.0:amd64
libboost-dev:amd64
libboost-exception1.58-dev:amd64
libboost-filesystem-dev:amd64
libboost-filesystem1.54.0:amd64
libboost-filesystem1.58-dev:amd64
libboost-filesystem1.58.0:amd64
libboost-graph-parallel1.58-dev
libboost-graph-parallel1.58.0
libboost-graph1.58-dev:amd64
libboost-graph1.58.0:amd64
libboost-iostreams1.58-dev:amd64
libboost-iostreams1.58.0:amd64
libboost-locale1.58-dev:amd64
libboost-locale1.58.0:amd64
libboost-log1.58-dev
libboost-log1.58.0
libboost-math1.58-dev:amd64
libboost-math1.58.0:amd64
libboost-mpi-python1.58-dev
libboost-mpi-python1.58.0
libboost-mpi1.58-dev
libboost-mpi1.58.0
libboost-program-options-dev:amd64
libboost-program-options1.54.0:amd64
libboost-program-options1.58-dev:amd64
libboost-program-options1.58.0:amd64
libboost-python1.58-dev
libboost-python1.58.0
libboost-random1.58-dev:amd64
libboost-random1.58.0:amd64
libboost-regex-dev:amd64
libboost-regex1.54.0:amd64
libboost-regex1.58-dev:amd64
libboost-regex1.58.0:amd64
libboost-serialization1.58-dev:amd64
libboost-serialization1.58.0:amd64
libboost-signals1.58-dev:amd64
libboost-signals1.58.0:amd64
libboost-system-dev:amd64
libboost-system1.54.0:amd64
libboost-system1.58-dev:amd64
libboost-system1.58.0:amd64
libboost-test1.58-dev:amd64
libboost-test1.58.0:amd64
libboost-thread-dev:amd64
libboost-thread1.54.0:amd64
libboost-thread1.58-dev:amd64
libboost-thread1.58.0:amd64
libboost-timer1.58-dev:amd64
libboost-timer1.58.0:amd64
libboost-wave1.58-dev:amd64
libboost-wave1.58.0:amd64
libboost1.58-all-dev
libboost1.58-dbg:amd64
libboost1.58-dev:amd64
libboost1.58-doc
libboost1.58-tools-dev
```

**Comment by Orvid** [comment]
Your libboost is likely compiled with 5.2, which is what's causing the issue, the same looks like it's the case with libglog. Build them both with 4.9, and HHVM itself as well and it should link fine.

**Comment by lbadger** [comment]
Thanks to @Orvid I was able to get it to compile! Thanks a lot! I'm glad I didn't have to roll back to 15.04.

**Comment by JoelMarcey** [comment]
:+1:

**Comment by maurocolella** [comment]
I just tried to build HHVM, on a "vanilla" Ubuntu Gnome with kernel 4.2.5-040205-generic

I did install gcc-4.9 first, but didn't pass any particular parameter to CMAKE, and just went with the straight building recipe for Ubuntu 14.04 / 14.10 / 15.04

It compiled flawlessly.
