### ISSUE TITLE
where can i find hphp/runtime/base/base-includes.h (hhvm 3.7)

### ISSUE THREAD

**Issue by bbaijang** [facebook/hhvm#5262]
after update hhvm version 3.6 to 3.7
when i rebuild msg-pack extension.
then i got this error :(

[ 12%] Building CXX object deps/msgpack/CMakeFiles/msgpack-c.dir/gcc_atomic.cpp.o
[ 25%] Building CXX object deps/msgpack/CMakeFiles/msgpack-c.dir/object.cpp.o
[ 37%] Building C object deps/msgpack/CMakeFiles/msgpack-c.dir/objectc.c.o
[ 50%] Building C object deps/msgpack/CMakeFiles/msgpack-c.dir/unpack.c.o
[ 62%] Building C object deps/msgpack/CMakeFiles/msgpack-c.dir/vrefbuffer.c.o
[ 75%] Building C object deps/msgpack/CMakeFiles/msgpack-c.dir/zone.c.o
[ 87%] Building C object deps/msgpack/CMakeFiles/msgpack-c.dir/version.c.o
Linking CXX static library libmsgpack-c.a
[ 87%] Built target msgpack-c
Scanning dependencies of target msgpack
[100%] Building CXX object CMakeFiles/msgpack.dir/ext_msgpack.cpp.o
/home/xsum/work/drizzt/msgpack-hhvm/ext_msgpack.cpp:17:45: fatal error: hphp/runtime/base/base-includes.h: No such file or directory
 #include "hphp/runtime/base/base-includes.h"
                                             ^
compilation terminated.
make[2]: *** [CMakeFiles/msgpack.dir/ext_msgpack.cpp.o] Error 1
make[1]: *** [CMakeFiles/msgpack.dir/all] Error 2
make: *** [all] Error 2

there is no base-includes.h in /usr/include/hphp
i use reeze's msgpack-hhvm (https://github.com/reeze/msgpack-hhvm)

please help me

**Comment by SiebelsTim** [comment]
See 91e07b951496b5bfbbb189fd5401e9dd5e711c43

You should be able to replace it with `ext/extension.h`

\cc @reeze

**Comment by reeze** [comment]
Thanks @SiebelsTim  
This related to https://github.com/reeze/msgpack-hhvm/issues/3 I will fix that soon. this could be closed since it is an external issue.

**Comment by bbaijang** [comment]
Thanks :)

**Comment by VietAnhDo** [comment]
When I replace base-includes.h with extension.h I impacted a error with g_context->write() like this: 
"error: ‘g_context’ was not declared in this scope g_context->write("abc");". Can someone help me how to fix this error or use another way for writing text.

**Comment by paulbiss** [comment]
You need to include hphp/runtime/base/execution-context.h if you want to use g_context

**Comment by VietAnhDo** [comment]
@paulbiss Thanks for your helping. Can you tell me where I can find hhvm reference? 
Thanks in advanced!
