### ISSUE TITLE
Compiling HHVM results in a compile error

### ISSUE THREAD

**Issue by derickr** [facebook/hhvm#6299]
Hi,

for some reason, my HHVM (3.9.1) compile started throwing:

```
../../../third-party/folly/libfolly.a(dynamic.cpp.o): In function `std::string* google::MakeCheckOpString<unsigned long, unsigned long>(unsigned long const&, unsigned long const&, char const*)':
/usr/include/glog/logging.h:672: undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
../../../third-party/folly/libfolly.a(Format.cpp.o): In function `std::string* google::MakeCheckOpString<int, int>(int const&, int const&, char const*)':
/usr/include/glog/logging.h:672: undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
collect2: error: ld returned 1 exit status
hphp/tools/bootstrap/CMakeFiles/gen-class-map.dir/build.make:123: recipe for target 'hphp/tools/bootstrap/gen-class-map' failed
make[2]: *** [hphp/tools/bootstrap/gen-class-map] Error 1
CMakeFiles/Makefile2:945: recipe for target 'hphp/tools/bootstrap/CMakeFiles/gen-class-map.dir/all' failed
make[1]: *** [hphp/tools/bootstrap/CMakeFiles/gen-class-map.dir/all] Error 2
Makefile:106: recipe for target 'all' failed
make: *** [all] Error 2
[GIT: (tags/HHVM-3.9.1)]
```

I've made sure glog is installed:

```
Selecting previously unselected package libgoogle-glog0v5.
(Reading database ... 268746 files and directories currently installed.)
Preparing to unpack .../libgoogle-glog0v5_0.3.4-0.1+b1_amd64.deb ...
Unpacking libgoogle-glog0v5 (0.3.4-0.1+b1) ...
Selecting previously unselected package libgoogle-glog-dev.
Preparing to unpack .../libgoogle-glog-dev_0.3.4-0.1+b1_amd64.deb ...
Unpacking libgoogle-glog-dev (0.3.4-0.1+b1) ...
Setting up libgoogle-glog0v5 (0.3.4-0.1+b1) ...
Setting up libgoogle-glog-dev (0.3.4-0.1+b1) ...
Processing triggers for libc-bin (2.19-19) ...
```

cheers,
Derick

**Comment by derickr** [comment]
Is there anyway I can help to help investigate this? libglog does have the symbol:

```
derick@whisky:/usr/include/glog $ nm /usr/lib/x86_64-linux-gnu/libglog.a | grep MakeCheckOpString
0000000000000000 W _ZN6google17MakeCheckOpStringIiiEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_RKT0_PKc
```

which parses to:
```
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<int, int>(int const&, int const&, char const*)
```

Could it be because libglog is compiled with GCC 5.2 and I am using 4.9 to compile HHVM?

As I said, I'm happy to do a debugging-over-IRC session :-)

cheers,
Derick

**Comment by wjywbs** [comment]
Can you try to build glog using gcc 4.9 or recompile it with the `-D_GLIBCXX_USE_CXX11_ABI=0` option with gcc 5.2?

**Comment by derickr** [comment]
If I compile libglog myself with 4.9, and link with that (after removing the Debian package for it), this error goes away.

However, the final linking of "CXX executable hhvm" now fails, I suspect for similar reasons, because of boost:

```
[100%] Linking CXX executable hhvm
/usr/include/boost/program_options/detail/value_semantic.hpp:167: error: undefined reference to 'boost::program_options::validate(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool*, int)'
/usr/include/boost/program_options/detail/value_semantic.hpp:167: error: undefined reference to 'boost::program_options::validate(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, std::string*, int)'
/usr/include/boost/program_options/errors.hpp:373: error: undefined reference to 'boost::program_options::validation_error::get_template(boost::program_options::validation_error::kind_t)'
/usr/include/boost/program_options/errors.hpp:373: error: undefined reference to 'boost::program_options::error_with_option_name::error_with_option_name(std::string const&, std::string const&, std::string const&, int)'
/home/derick/dev/facebook-hhvm/hphp/runtime/base/program-functions.cpp:1094: error: undefined reference to 'boost::program_options::option_description::long_name() const'
/home/derick/dev/facebook-hhvm/hphp/runtime/base/program-functions.cpp:1104: error: undefined reference to 'boost::program_options::option_description::format_name() const'
/usr/include/boost/program_options/detail/convert.hpp:79: error: undefined reference to 'boost::program_options::to_internal(std::string const&)'
/usr/include/boost/program_options/detail/parsers.hpp:43: error: undefined reference to 'boost::program_options::detail::cmdline::cmdline(std::vector<std::string, std::allocator<std::string> > const&)'
/usr/include/boost/program_options/detail/value_semantic.hpp:19: error: undefined reference to 'boost::program_options::arg'
/usr/include/boost/program_options/detail/value_semantic.hpp:146: error: undefined reference to 'boost::program_options::validate(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, std::string*, int)'
/usr/include/boost/program_options/detail/value_semantic.hpp:150: error: undefined reference to 'boost::program_options::invalid_option_value::invalid_option_value(std::string const&)'
/usr/include/boost/program_options/detail/value_semantic.hpp:92: error: undefined reference to 'boost::program_options::invalid_option_value::invalid_option_value(std::string const&)'
/home/derick/dev/facebook-hhvm/hphp/runtime/base/program-functions.cpp:1229: error: undefined reference to 'boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:vtable for boost::exception_detail::error_info_injector<boost::program_options::invalid_option_value>: error: undefined reference to 'boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:vtable for boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::invalid_option_value> >: error: undefined reference to 'boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:vtable for boost::exception_detail::error_info_injector<boost::program_options::validation_error>: error: undefined reference to 'boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:vtable for boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::validation_error> >: error: undefined reference to 'boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:vtable for boost::program_options::typed_value<std::string, char>: error: undefined reference to 'boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:vtable for boost::program_options::typed_value<std::vector<std::string, std::allocator<std::string> >, char>: error: undefined reference to 'boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:vtable for boost::program_options::typed_value<int, char>: error: undefined reference to 'boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:vtable for boost::program_options::typed_value<bool, char>: error: undefined reference to 'boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
/home/derick/dev/facebook-hhvm/hphp/compiler/compiler.cpp:206: error: undefined reference to 'boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
/usr/include/boost/program_options/detail/parsers.hpp:77: error: undefined reference to 'boost::program_options::detail::cmdline::set_additional_parser(boost::function1<std::pair<std::string, std::string>, std::string const&>)'
/usr/include/boost/program_options/detail/value_semantic.hpp:19: error: undefined reference to 'boost::program_options::arg'
/home/derick/dev/facebook-hhvm/hphp/hhbbc/main.cpp:70: error: undefined reference to 'boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
/home/derick/dev/facebook-hhvm/hphp/hhbbc/main.cpp:107: error: undefined reference to 'boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
/usr/include/boost/program_options/detail/value_semantic.hpp:92: error: undefined reference to 'boost::program_options::invalid_option_value::invalid_option_value(std::string const&)'
/usr/include/boost/program_options/detail/value_semantic.hpp:92: error: undefined reference to 'boost::program_options::invalid_option_value::invalid_option_value(std::string const&)'
collect2: error: ld returned 1 exit status
hphp/hhvm/CMakeFiles/hhvm.dir/build.make:365: recipe for target 'hphp/hhvm/hhvm' failed
make[2]: *** [hphp/hhvm/hhvm] Error 1
CMakeFiles/Makefile2:2229: recipe for target 'hphp/hhvm/CMakeFiles/hhvm.dir/all' failed
make[1]: *** [hphp/hhvm/CMakeFiles/hhvm.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
[GIT: (tags/HHVM-3.9.1)]
```

**Comment by derickr** [comment]
I managed to compile this now - with the hacks described at http://derickrethans.nl/hhvm-gcc-52.html

**Comment by jrobeson** [comment]
@derickr:  you might get hhvm working properly with no hacks if you apply this patch: https://github.com/facebook/hhvm/pull/6298

**Comment by derickr** [comment]
This no longer is an issue for me, as I compile with 4.9 without problems now.
