### ISSUE TITLE
Build fails with libxml2 2.9.8

### ISSUE THREAD

**Issue by usox** [facebook/hhvm#8200]
After updating libxml2 from 2.9.7 to 2.9.8 I'm not able to build hhvm anymore. Downgrading to back to 2.9.7 fixes the problem. So I guess it's somehow hhvm related...

### HHVM Version
Tested with 3.24.5/6/7 and 3.25.3

### Operating System and Version
Gentoo Linux

### Standalone code, or other way to reproduce the problem
```
/var/tmp/portage/dev-php/hhvm-3.24.7/work/hhvm-3.24.7/hphp/runtime/ext/domdocument/ext_domdocument.cpp: In function ‘xmlNode* HPHP::php_dom_libxml_hash_iter(xmlHashTable*, int)’:
/var/tmp/portage/dev-php/hhvm-3.24.7/work/hhvm-3.24.7/hphp/runtime/ext/domdocument/ext_domdocument.cpp:1471:43: error: invalid conversion from ‘void (*)(void*, void*, xmlChar*) {aka void (*)(void*, void*, unsigned char*)}’ to ‘xmlHashScanner {aka void (*)(void*, void*, const unsigned char*)}’ [-fpermissive]
     xmlHashScan(ht, itemHashScanner, &iter);
                                           ^
In file included from /usr/include/libxml2/libxml/parser.h:18:0,
                 from /var/tmp/portage/dev-php/hhvm-3.24.7/work/hhvm-3.24.7/hphp/runtime/ext/domdocument/ext_domdocument_includes.h:23,
                 from /var/tmp/portage/dev-php/hhvm-3.24.7/work/hhvm-3.24.7/hphp/runtime/ext/domdocument/ext_domdocument.h:26,
                 from /var/tmp/portage/dev-php/hhvm-3.24.7/work/hhvm-3.24.7/hphp/runtime/ext/domdocument/ext_domdocument.cpp:18:
/usr/include/libxml2/libxml/hash.h:212:4: note:   initializing argument 2 of ‘void xmlHashScan(xmlHashTablePtr, xmlHashScanner, void*)’
    xmlHashScan (xmlHashTablePtr table,
    ^~~~~~~~~~~
/var/tmp/portage/dev-php/hhvm-3.24.7/work/hhvm-3.24.7/hphp/runtime/ext/domdocument/ext_domdocument.cpp: In function ‘xmlNode* HPHP::php_dom_libxml_notation_iter(xmlHashTable*, int)’:
/var/tmp/portage/dev-php/hhvm-3.24.7/work/hhvm-3.24.7/hphp/runtime/ext/domdocument/ext_domdocument.cpp:1484:43: error: invalid conversion from ‘void (*)(void*, void*, xmlChar*) {aka void (*)(void*, void*, unsigned char*)}’ to ‘xmlHashScanner {aka void (*)(void*, void*, const unsigned char*)}’ [-fpermissive]
     xmlHashScan(ht, itemHashScanner, &iter);
                                           ^
In file included from /usr/include/libxml2/libxml/parser.h:18:0,
                 from /var/tmp/portage/dev-php/hhvm-3.24.7/work/hhvm-3.24.7/hphp/runtime/ext/domdocument/ext_domdocument_includes.h:23,
                 from /var/tmp/portage/dev-php/hhvm-3.24.7/work/hhvm-3.24.7/hphp/runtime/ext/domdocument/ext_domdocument.h:26,
                 from /var/tmp/portage/dev-php/hhvm-3.24.7/work/hhvm-3.24.7/hphp/runtime/ext/domdocument/ext_domdocument.cpp:18:
/usr/include/libxml2/libxml/hash.h:212:4: note:   initializing argument 2 of ‘void xmlHashScan(xmlHashTablePtr, xmlHashScanner, void*)’
    xmlHashScan (xmlHashTablePtr table,
    ^~~~~~~~~~~
make[2]: *** [hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/build.make:1143: hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/domdocument/ext_domdocument.cpp.o] Error 1

```

**Comment by NamedKitten** [comment]
Can confirm building on arch linux at latest commit of hhvm. Reverting to libxml 2.9.7 also fixes the issue.

**Comment by fredemmott** [comment]
Sorry - unfortunately, I'm not able to spend much time on issues that don't exist on distributions that we don't support. I'll happily review a pull request to fix this, or likely fix it when/if it becomes an issue in a new Ubuntu release

**Comment by Wilfred** [comment]
> `invalid conversion from [...] void (*)(void*, void*, unsigned char*)}’ to ‘xmlHashScanner {aka void (*)(void*, void*, const unsigned char*)}’`

Looks like libxml2 has added `const` to some parameters and we error on this particular warning.

**Comment by fredemmott** [comment]
Now affecting supported platforms
