### ISSUE TITLE
Regression test hphp/test/slow/rx/body/fail.php consistently fails

### ISSUE THREAD

**Issue by swalk-cavium** [facebook/hhvm#8403]
### HHVM Version

lab-3:/data2/swalk/play.121418a/hhvm$ ./hphp/hhvm/hhvm --version
HipHop VM 3.30.0-dev (rel)
Compiler: heads/master-0-g4477e1a390fb2938663a629fe7c81b37f6175d77
Repo schema: ed8df6d7fc054b87e500bd7e541a7222a3a409db

### Operating System and Version

lab-3:/data2/swalk/play.121418a/hhvm$ uname -a
Linux lab-3 4.2.0 #1 SMP Wed Nov 25 14:00:54 CST 2015 aarch64 aarch64 aarch64 GNU/Linux

### Standalone code, or other way to reproduce the problem

hphp/test/run -v -m interp  hphp/test/slow/rx/body/fail.php

### Actual result

lab-3:/data2/swalk/play.121418a/hhvm$ hphp/test/run -v -m interp  hphp/test/slow/rx/body/fail.php
You are using the binary located at: ./hphp/hhvm/hhvm
Running 1 tests in 1 threads (0 in serial)

Warning: Compilation failed: missing ) at offset 118 in /data2/swalk/play.121418a/hhvm/hphp/test/run.php on line 1748

Warning: Compilation failed: missing ) at offset 118 in /data2/swalk/play.121418a/hhvm/hphp/test/run.php on line 1748

Warning: Compilation failed: unmatched parentheses at offset 1 in /data2/swalk/play.121418a/hhvm/hphp/test/run.php on line 1748
hphp/test/slow/rx/body/fail.php FAILED (3.38s)

1 tests failed

### Expected result

pass

I'm not sure why it's crying about the (unchanged) driver, but it looks like
the actual output does not match the fail.php.expectregex file when you 
compare manually.

I think this was introduced by https://github.com/facebook/hhvm/commit/d46a624307a846d56a2381034f4c0732bed3749a

**Comment by alexeyt** [comment]
I spoke to someone with more context on why the test driver works this way, and it seems that, while it's allowed for tests to use multi-line regexes in .expectregex files, the test driver's diff functionality when using .expectregex files is best-effort, and is allowed to produce the warnings you see and fail to produce useful diff output (it does work correctly in the absence of multi-line regexes). So, it looks like the warnings are purely a red herring, and we need to manually inspect the .out file to see what went wrong.

**Comment by swalk-cavium** [comment]
```
swalk@lab-3:/data2/swalk/play.010619a/hhvm$ cat hphp/test/slow/rx/body/fail.php.out
Verification Error (unit /data2/swalk/play.010619a/hhvm/hphp/test/slow/rx/body/fail.php func main): Print cannot appear in Rx function

Verification failed for unit /data2/swalk/play.010619a/hhvm/hphp/test/slow/rx/body/fail.php. Re-run with HHVM_VERIFY_VERBOSE=1 to see more details.

Fatal error: Uncaught Error: A bytecode verification error was detected in /data2/swalk/play.010619a/hhvm/hphp/test/slow/rx/body/fail.php:-1
Stack trace:
#0 {main}

**Comment by swalk-cavium** [comment]
Hello @alexeyt,
That's what I'm seeing on a built from yesterday using
```
hphp/test/run -v -m interp hphp/test/slow/rx/body/fail.php

swalk@lab-3:/data2/swalk/play.010619a/hhvm$ ./hphp/hhvm/hhvm --version
HipHop VM 3.30.0-dev (rel)
Compiler: heads/master-0-gaa72036407cd18d6db82e9911aef30f976b5744c
Repo schema: 5547fa390b53d92002aa678fb1eec5ca94f6ef62

swalk@lab-3:/data2/swalk/play.010619a/hhvm$ uname -a
Linux lab-3 4.2.0 #1 SMP Wed Nov 25 14:00:54 CST 2015 aarch64 aarch64 aarch64 GNU/Linux
